### PR TITLE
End-to-end testing

### PR DESCRIPTION
**Pull request by jonas**
... in preparation for adding bindings to the project.

### CODE REVIEW

**Comment by kornilova-l** [comment]
Maybe the problem with failing tests is ubuntu-related because I have the same errors on my laptop with ubuntu 17.10

**Comment by kornilova-l** [comment]
Currently I have strange problem with `ar`:
```
[info] Running ar -rs /home/lk/projects/gsoc/scala-native-bindgen/tests/samples/target/scala-2.11/native/bindgen/libbindgentests.a /home/lk/projects/gsoc/scala-native-bindgen/tests/samples/target/scala-2.11/native/bindgen/Function.c.o
[error] ar: creating /home/lk/projects/gsoc/scala-native-bindgen/tests/samples/target/scala-2.11/native/bindgen/libbindgentests.a
```
it works fine if I simply copy-paste it to terminal

**Comment by jonas** [comment]
Adding `c` to the `ar` arguments removes the message written to `stderr`.

**Comment by jonas** [comment]
Refs #51 - Only adds tests for `Function.h`.

**Comment by kornilova-l** [comment]
Awesome commit!

**Pull request merged**
