### PR TITLE
Bindgen docker image

### PR DESCRIPTION
**Pull request by jonas**

### CODE REVIEW

**Comment by kornilova-l** [comment]
When I tried to run the container it gave me the error:
```
/bin/sh: 1: [scala-native-bindgen]: not found
```
`docker inspect` told me that the entrypoint is
```json
"Entrypoint": [
    "/bin/sh",
    "-c",
    "[scala-native-bindgen]"
],
```
I changed the ENTRYPOINT line in the Dockerfile to ["scala-native-bindgen"]
Now it works okay

**Comment by kornilova-l** [comment]
What will be the script to generate bindings using container?
I tried to run this:
```bash
$ docker run -v /usr/include:/src --rm scalabindgen/scala-native-bindgen /src/ctype.h --name ctype --
```
but it gives this errors:
```
/src/ctype.h:25:10: error: 'features.h' file not found with <angled> include; use "quotes" instead
#include <features.h>
         ^~~~~~~~~~~~
         "features.h"
In file included from /src/ctype.h:25:
/src/features.h:397:10: error: 'stdc-predef.h' file not found with <angled> include; use "quotes" instead
#include <stdc-predef.h>
         ^~~~~~~~~~~~~~~
         "stdc-predef.h"
/src/features.h:419:12: fatal error: 'sys/cdefs.h' file not found
#  include <sys/cdefs.h>
           ^~~~~~~~~~~~~
3 errors generated.
Error while processing /src/ctype.h.
```

Seems like the image lacks C headers:
```bash
$ docker run --rm --entrypoint=ls scalabindgen/scala-native-bindgen /usr/include
# empty output
```

**Comment by kornilova-l** [comment]
@jonas, `-v /usr/include:/usr/include` works, I'll publish instructions today

**Comment by kornilova-l** [comment]
@jonas, do you still working on following in this branch?
> My plan is to configure so that Travis will update latest on merge to master and a named version for each tag/release.

Or this branch may be merged?

**Comment by jonas** [comment]
Yes I will work on that this weekend.

**Comment by kornilova-l** [comment]
:+1:

**Comment by jonas** [comment]
However, we can merge the PR as is and I can create a new one with changes to push images from CI.

**Comment by jonas** [comment]
Thanks a lot for fixing the entrypoint configuration. I will look into adding a test.

**Pull request merged**
