### PR TITLE
Generate constructor helper

### LINKED ISSUE #155: Create struct constructor helper
I think struct constructor helper should be in separate `constructors` object because it will make bindings more readable.
`constructors` object imports `implicits` and it makes it possible to reuse setters. 
```scala
@native.extern
object mylib {
  type struct_point = native.CStruct2[native.CInt, native.CInt]
  
  object implicits {
    implicit class struct_point_ops(val p: native.Ptr[struct_point]) extends AnyVal {
      def x: native.CInt = !p._1
      def x_=(value: native.CInt): Unit = !p._1 = value
      def y: native.CInt = !p._2
      def y_=(value: native.CInt): Unit = !p._2 = value
    }
    def struct_point()(implicit z: native.Zone): native.Ptr[struct_point] = native.alloc[struct_point]
  }

  object constructors {
    import implicits._
    object struct_point {
      def apply(x: native.CInt, y: native.CInt)(implicit z: native.Zone): native.Ptr[struct_point] = {
        val ptr = native.alloc[struct_point]
        ptr.x = x
        ptr.y = y
        ptr
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by kornilova-l**
Closes #155

To do:
- [x] update tutorial example in readme.

### CODE REVIEW

**Comment by kornilova-l** [comment]
This PR tests will be fixed with new version of plugin #164

**Comment by jonas** [comment]
Should I merge the other PR and create a new RC?

**Comment by kornilova-l** [comment]
Yes

**Comment by jonas** [comment]
Done. I assume you want to add the following setting to the `docs` project.

```scala
nativeBindgenPath := {
  Some((ThisBuild / baseDirectory).value / "bindgen/target/scala-native-bindgen")
}
```

**Pull request merged**
